### ISSUE TITLE
Use gnome.post_install() instead of manual script

### ISSUE THREAD

**Issue by ryonakano** [ryonakano/reco#158]
Found at https://github.com/alexkdeveloper/desktop-files-creator/blob/6221b25e7619d19c7d4233ad35da8893a92b89d3/meson.build#L23-L27.

Docs: https://mesonbuild.com/Gnome-module.html#gnomepost_install

**Comment by eli-schwartz** [comment]
https://github.com/ryonakano/reco/blob/3a5df358418f091180f2bb6fa356348c543aaf6d/meson.build#L5

Note that you'd need to bump your minimum version of Meson to 0.57.0 in order to make this change. That should be available most places though, as long as you don't feel the need to support oldstable versions of a distro.

**Comment by ryonakano** [comment]
@eli-schwartz Wow, thank you for your information! I'll take care of it.
