### ISSUE TITLE
Add recording indication

### ISSUE THREAD

**Issue by ryonakano** [ryonakano/reco#179]
Originally from https://github.com/ryonakano/reco/issues/175#issuecomment-1280885151:

> If I can just pick your brain for a quick feature request, it would be nice to have some sort of indication of signal, maybe just a little red light when there is speech, something... because I just made a recording without my microphone plugged in and didn't even notice until I saw the file size :)

**Comment by nekohayo** [comment]
Perhaps you could take inspiration from the [gnome-sound-recorder's realtime waveform visualization](https://gitlab.gnome.org/GNOME/gnome-sound-recorder/-/blob/master/src/waveform.js) implementation?

**Comment by nekohayo** [comment]
Other alternatives include:
* Using GtkProgressbar or GtkLevelbar to indicate volume of the microphone, system, or both. This is what [PulseCaster](https://github.com/stickster/pulsecaster) does.
* Imitating Pitivi's [new vumeter widget](https://gitlab.gnome.org/GNOME/pitivi/-/issues/595) implementation

**Comment by ryonakano** [comment]
Yeah, it would be ideal to make something similar to the indication seen in GNOME Sound Recorder; showing waves would be common in this situation.

**Comment by nekohayo** [comment]
The only thing is, I'm not entirely sure (yet) if the waves "as implemented in g-s-r" are the ones causing [this CPU-eating performance issue](https://gitlab.gnome.org/GNOME/gnome-sound-recorder/-/issues/96) on startup, but since your application is simpler and not trying to list all previous recordings, only show a live waveform while it's happening, then you will probably not have the same problem.
