### ISSUE TITLE
Feature request: run script after saving file

### ISSUE THREAD

**Issue by afonsoguerra** [ryonakano/reco#223]
Thank you very much for all the updates. It's working wonderfully and I'm using it right now to dictate this text. 

If I can have one last request for the next version, would it be possible to automatically run a shell script at the end of recording?

That would be perfect for my use case, in which I just want to record a small voice recording and then transcribe it. 

Thanks a lot for your work on this and congratulations on your five years of the project

**Comment by ryonakano** [comment]
I'm sorry for my late response. I'm afraid that I'm not willing to let Reco run an arbitrarily script after recording because I think it's a bit out of its responsibility as an audio recorder. Also, execution of commands are strongly limited under the sandboxed environment in Flatpak, so running a script may not always works well even if we implemented this feature.

Instead, however, it's possible to implement the feature that can quit the app after recording, and then I think you can fulfill your needs by creating a script like this and running it when you want to record and transcribe:

```bash
#!/bin/bash

flatpak run com.github.ryonakano.reco

# Call your script or maybe directly call your transcribe app (?) here
# Once Reco quits with the "quit the app after recording" feature, that script or procedure is executed
```

**Comment by afonsoguerra** [comment]
Hey, thanks for the reply! I've ended up setting up a different script that just looks for files in the reco output directory, if it finds one it hasn't transcribed yet, it gets transcribed. If works well, so I'll close this!
