### ISSUE TITLE
Cannot view the microphone names if they are long

### ISSUE THREAD

**Issue by jasiralavi** [ryonakano/reco#224]
Thanks for the great app!
Just a concern though, I'm unable to view the microphone names in the app window.

I think you could either let user be able to resize the app window. 
Or you could show the full name as a tooltip while hovering over it.

![image](https://github.com/ryonakano/reco/assets/16372030/11719b99-b0ba-4ef9-b080-2ba90f29fb3f)

This is how it shows on my system controls:

![image](https://github.com/ryonakano/reco/assets/16372030/f0a3d9d7-1b32-4d53-9687-6c55c4c3e9b9)

**Comment by diaconic** [comment]
I think an improvement that could be made to this (besides giving the dropdown a tooltip displaying the full name as they suggested) is changing the text truncation to insert ellipses in the middle of the device name rather than at the end. Many audio devices have prefixes and such but basically all of them end differently, so it would be useful to see some of both sides at the same time.
