### ISSUE TITLE
Suggestion: Keep old release data around

### ISSUE THREAD

**Issue by cassidyjames** [ryonakano/reco#72]
We use old release data in AppCenter and on the AppCenter website so users can see how often an app is updated, or to show them the changes between their current version and the latest version (if there's more than one release between them). To do so, apps need to keep at least some historical release data around in the AppData.

**Comment by ryonakano** [comment]
I always overrode old release notes because I thought it might be a burden for translators to translate strings that are never shown neither in AppCenter nor the AppCenter website (there are about 150 strings in Files/Extra for example). I guess old release notes are not shown in AppCenter at the moment, right? Although they are shown in the AppCenter website, they are not shown as translated, so translation works for release notes have fewer meanings at the moment.

However, keeping them for comparison or checking development activities would be useful indeed. So, I have a question: can I revive the old release notes or should I keep this mind from the next release (I mean, does reviving them cause any issues in packaging or something like that)?

**Comment by cassidyjames** [comment]
@ryonakano I believe AppCenter on elementary OS does currently display all releases between the installed version and the latest version; for example, if someone hadn't booted up their elementary machine for a couple months (or just hadn't updated in that time), they would see the notes for all the releases that had been made in that time.

Reviving them should not cause any issues since they're tagged with the version number; AppStream and AppCenter should be able to pair them up correctly just fine.
